sudo: required
services:
  - docker

before_install:
  - docker build -t renatodvm/docker-react .

script:
  - docker run -e CI=true renatodvm/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-901681299924"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
